import { Inter } from "next/font/google";
import "./globals.css";
import { Nunito } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const nunito = Nunito({
    weight: ['400', '700', '800'],
    subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={nunito.className}>{children}</body>
    </html>
  );
}
